# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
  - r: 3.5
before_install:
  sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable;
  sudo apt-get -y update;
  sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
