#' Convert geogrid output to sf object
#'
#' Takes the output from calculate_geom and converts it to a tidy sf object.
#'
#' @param geom Geom generated by calculate_geom
#' @return An sf object containing the grid geometry
#' @keywords internal

tidy_geom <- function(geom) {
  grid <- sf::st_as_sf(geom[[2]])
  return(grid)
}
