#' Calculate grid based on type and seed
#'
#' @param geom Geom generated by calculate_geom
#' @return Tidy version of the geom
#' @keywords internal

tidy_geom <- function(geom){
  grid <- sf::st_as_sf(geom[[2]])
  return(grid)
}
